"""empty message

Revision ID: 9d356cd51db7
Revises: 
Create Date: 2020-04-30 14:36:27.635464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d356cd51db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('twitter_key', sa.String(length=120), nullable=True),
    sa.Column('twitter_secret', sa.String(length=120), nullable=True),
    sa.Column('twitter_user_info', sa.PickleType(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('auto_post_interval', sa.Interval(), nullable=True),
    sa.Column('auto_post_active_start', sa.Time(), nullable=True),
    sa.Column('auto_post_active_end', sa.Time(), nullable=True),
    sa.Column('auto_post_refresh', sa.Interval(), nullable=True),
    sa.Column('hashtag_dict', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('postedfb', sa.Boolean(), nullable=True),
    sa.Column('postedtw', sa.Boolean(), nullable=True),
    sa.Column('do_not_post', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rss_id', sa.Integer(), nullable=True),
    sa.Column('auto_set_post_time', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('hashtags', sa.String(length=140), nullable=True),
    sa.Column('auto_post_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('rss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('posts', sa.PickleType(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_timestamp'), 'rss', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rss_timestamp'), table_name='rss')
    op.drop_table('rss')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
