"""empty message

Revision ID: b3c630ceab2d
Revises: 06912f2cc637
Create Date: 2020-05-01 16:06:25.099229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c630ceab2d'
down_revision = '06912f2cc637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('character_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'character_count')
    # ### end Alembic commands ###
