"""empty message

Revision ID: b90e56162383
Revises: b3c630ceab2d
Create Date: 2020-05-07 02:18:26.437021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90e56162383'
down_revision = 'b3c630ceab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_refresh', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_refresh')
    # ### end Alembic commands ###
